### ISSUE TITLE
클래스 관련 자바 파일 분리

### ISSUE THREAD

**Issue by wltn716** [shinah/softwareEngineering#1]
한 자바파일에 main함수 포함한 클래스와 그 외 클래스들 모두 작성하는 것 보다,
각각 기능별로 분리해서 여러개의 자바파일에 작성하는게 좋을 것 같은데 어떻게 생각하시나요!

**Comment by shinah** [comment]
오 좋은 생각 같습니다! 메인함수 클래스를 따로 두는게 좋을거 같군요!

**Comment by linibell** [comment]
저도 좋아요~~~~~~><

**Comment by shinah** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ혼자 모하심ㅋㅋㅋㅋㅋㅋ

**Comment by linibell** [comment]
언니 뭐해여....?

**Comment by linibell** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ짱웃곀ㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by shinah** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by shinah** [comment]
업데이트가 모야모야
